# Generated by Django 5.1.2 on 2024-11-06 02:27

from django.db import migrations, models

import editar_formulario.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditarCampos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("municipio", models.JSONField(default=editar_formulario.models.Default)),
                ("institucion", models.JSONField(default=editar_formulario.models.DefaultInstitucion)),
                ("dane", models.JSONField(default=editar_formulario.models.DefaultDane)),
                ("sede", models.JSONField(default=editar_formulario.models.DefaultSede)),
                ("remitidoPor", models.JSONField(default=editar_formulario.models.DefaultRemitidoPor)),
                ("nombreRemitidoPor", models.JSONField(default=editar_formulario.models.Default)),
                (
                    "posiblesMotivosDeAtencion",
                    models.JSONField(default=editar_formulario.models.DefaultPosiblesMotivosDeAtencion),
                ),
                ("lineaDeAtencion", models.JSONField(default=editar_formulario.models.DefaultLineaDeAtencion)),
                ("tipoDeAtencion", models.JSONField(default=editar_formulario.models.DefaultTipoDeAtencion)),
                (
                    "entidadPrestadoraDeSalud",
                    models.JSONField(default=editar_formulario.models.DefaultEntidadPrestadoraDeSalud),
                ),
                ("tipoDocumentoEstudiante", models.JSONField(default=editar_formulario.models.Default)),
                ("gradoEscolaridad", models.JSONField(default=editar_formulario.models.DefaultGradoEscolaridad)),
                ("sexo", models.JSONField(default=editar_formulario.models.DefaultSexo)),
                ("genero", models.JSONField(default=editar_formulario.models.DefaultGenero)),
                ("parentesco", models.JSONField(default=editar_formulario.models.DefaultParentesco)),
                ("ocupacion", models.JSONField(default=editar_formulario.models.DefaultOcupacion)),
                ("nivelEducativo", models.JSONField(default=editar_formulario.models.DefaultNivelEducativo)),
                ("estadoCivil", models.JSONField(default=editar_formulario.models.DefaultEstadoCivil)),
                ("tipoFamilia", models.JSONField(default=editar_formulario.models.DefaultTipoDeFamilia)),
                (
                    "condicionDiscapacidad",
                    models.JSONField(default=editar_formulario.models.DefaultCondicionDiscapacidad),
                ),
                ("tipoDiscapacidad", models.JSONField(default=editar_formulario.models.DefaultTipoDiscapacidad)),
                (
                    "talentoYCapacidadesExepcionales",
                    models.JSONField(default=editar_formulario.models.DefaultTalentoYCapacidadesExepcionales),
                ),
                ("activacionRuta", models.JSONField(default=editar_formulario.models.DefaultActivacionDeRuta)),
                ("estadoCaso", models.JSONField(default=editar_formulario.models.DefaultEstadoDelCaso)),
                ("nombreOrientadora", models.JSONField(default=editar_formulario.models.DefaultNombreOrientadora)),
            ],
            options={
                "verbose_name": "Editar Campos",
                "verbose_name_plural": "Editar Campos",
            },
        ),
    ]
