# Generated by Django 5.1.2 on 2024-11-06 17:55

from django.db import migrations, models

import editar_formulario.models


class Migration(migrations.Migration):
    dependencies = [
        ("editar_formulario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editarcampos",
            name="nombreEstudiante",
            field=models.JSONField(default=editar_formulario.models.Default),
        ),
    ]
