# Generated by Django 5.1.2 on 2024-11-21 21:41

from django.db import migrations, models

import editar_formulario.models


class Migration(migrations.Migration):
    dependencies = [
        ("editar_formulario", "0002_editarcampos_nombreestudiante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editarcampos",
            name="municipio",
            field=models.JSONField(default=editar_formulario.models.DefaultMunicipio),
        ),
    ]
