# Generated by Django 5.1.2 on 2024-10-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('institucion', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('dane', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('sede', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('remitidoPor', models.TextField(blank=True, default='no establecido', null=True)),
                ('nombreRemitidoPor', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('posiblesMotivosDeAtencion', models.TextField(blank=True, default='no establecido', null=True)),
                ('lineaDeAtencion', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('tipoDeAtencion', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('entidadPrestadoraDeSalud', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('personaDeConfianza', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('nombreEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('tipoDocumentoEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('numeroDocumentoEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('gradoEscolaridad', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('numeroTelefonoEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('epsEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('edadEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('fechaNacimientoEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('lugarNacimientoEstudiante', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('telefonoAcudiente', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('documentoAcudiente', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('parentescoAcudiente', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('sexo', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('genero', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('parentesco', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('nombre', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('edad', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('ocupacion', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('nivelEducativo', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('estadoCivil', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('numeroHijos', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('lugarResidencia', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('tipoFamilia', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('hogarYBienestar', models.TextField(blank=True, default='no establecido', null=True)),
                ('espectativasEntrevistado', models.TextField(blank=True, default='no establecido', null=True)),
                ('condicionDiscapacidad', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('tipoDiscapacidad', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('talentoYCapacidadesExepcionales', models.TextField(blank=True, default='no establecido', null=True)),
                ('relatoEntrevistado', models.TextField(blank=True, default='no establecido', null=True)),
                ('observaciones', models.TextField(blank=True, default='no establecido', null=True)),
                ('activacionRuta', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('procesosConvivencia', models.TextField(blank=True, default='no establecido', null=True)),
                ('estadoCaso', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('fechaProximoSeguimiento', models.DateTimeField(blank=True, null=True)),
                ('nombreOrientadora', models.CharField(blank=True, default='no establecido', max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('resumenRelato', models.TextField(blank=True, null=True)),
                ('acuerdosPrevios', models.ManyToManyField(blank=True, related_name='acuerdosPrevios', to='registro_de_atencion.archivo')),
                ('compromisoEstudiantes', models.ManyToManyField(blank=True, related_name='compromisoEstudiantes', to='registro_de_atencion.archivo')),
                ('compromisoPadres', models.ManyToManyField(blank=True, related_name='compromisoPadres', to='registro_de_atencion.archivo')),
                ('piar', models.ManyToManyField(blank=True, related_name='piar', to='registro_de_atencion.archivo')),
                ('remision', models.ManyToManyField(blank=True, related_name='remision', to='registro_de_atencion.archivo')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
