# Generated by Django 5.1.2 on 2024-12-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to="archivos/")),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombreEstudiante", models.CharField(max_length=500)),
                ("tipoDocumentoEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("numeroDocumentoEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("sexo", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("genero", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("gradoEscolaridad", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("numeroTelefonoEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("epsEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("edadEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("fechaNacimientoEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("lugarNacimientoEstudiante", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("direccion", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("municipio", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("institucion", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("dane", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("sede", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("entidadPrestadoraDeSalud", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("personaDeConfianza", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("telefonoAcudiente", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("documentoAcudiente", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("parentescoAcudiente", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("edadAcudiente", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("ocupacionAcudiente", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("nivelEducativo", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("estadoCivil", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("numeroHijos", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("lugarResidencia", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("tipoFamilia", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("hogarYBienestar", models.TextField(blank=True, default="no establecido")),
                ("condicionDiscapacidad", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("tipoDiscapacidad", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("talentoYCapacidadesExepcionales", models.TextField(blank=True, default="no establecido")),
                (
                    "compromisoEstudiantes",
                    models.ManyToManyField(
                        blank=True, related_name="compromisoEstudiantes", to="registro_de_atencion.archivo"
                    ),
                ),
                (
                    "compromisoPadres",
                    models.ManyToManyField(
                        blank=True, related_name="compromisoPadres", to="registro_de_atencion.archivo"
                    ),
                ),
                ("piar", models.ManyToManyField(blank=True, related_name="piar", to="registro_de_atencion.archivo")),
            ],
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consecutivo", models.IntegerField(blank=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                ("remitidoPor", models.TextField(blank=True, default="no establecido")),
                ("nombreRemitidoPor", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("posiblesMotivosDeAtencion", models.TextField(blank=True, default="no establecido")),
                ("lineaDeAtencion", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("tipoDeAtencion", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("relatoEntrevistado", models.TextField(blank=True, default="no establecido")),
                ("espectativasEntrevistado", models.TextField(blank=True, default="no establecido")),
                ("observaciones", models.TextField(blank=True, default="no establecido")),
                ("activacionRuta", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("procesosConvivencia", models.TextField(blank=True, default="no establecido")),
                ("estadoCaso", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("fechaProximoSeguimiento", models.DateTimeField(blank=True, null=True)),
                ("nombreOrientadora", models.CharField(blank=True, default="no establecido", max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("resumen", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True)),
                ("resumenRelato", models.TextField(blank=True)),
                (
                    "acuerdosPrevios",
                    models.ManyToManyField(
                        blank=True, related_name="acuerdosPrevios", to="registro_de_atencion.archivo"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="registro_de_atencion.estudiante",
                    ),
                ),
                (
                    "remision",
                    models.ManyToManyField(blank=True, related_name="remision", to="registro_de_atencion.archivo"),
                ),
            ],
            options={
                "verbose_name": "Registro",
                "verbose_name_plural": "Registros",
            },
        ),
    ]
