# Generated by Django 5.1.2 on 2024-11-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registro_de_atencion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="nombreEstudiante",
            field=models.CharField(default="John Doe", max_length=500),
            preserve_default=False,
        ),
    ]
