# Generated by Django 5.1.2 on 2024-11-26 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registro_de_atencion", "0002_alter_registro_nombreestudiante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registro",
            name="form_data",
        ),
    ]
